### ISSUE TITLE
Rewrite README

### ISSUE THREAD

**Issue by duc0905** [vietcodes5/web#1]
Installation steps.

- how to clone
- how to install dependencies
- how to run development server
- steps to contribute code

**Comment by duc0905** [comment]
@tiuphun ơi em sắp xong chưa...

**Comment by tiuphun** [comment]
em đang fix npm trên máy e, nó bị lỗi rồi :crying_cat_face: 
terminal của linux khó chịu vò lò

*chiều nay có nhé *

**Comment by tiuphun** [comment]
check check anh ơi xem thiếu gì hong @duc0905
