### ISSUE TITLE
Make Homepage

### ISSUE THREAD

**Issue by duc0905** [vietcodes5/web#13]
Làm trang Homepage theo design của anh Sơn Ke

Edit file pages/home.js

![image](https://user-images.githubusercontent.com/34796126/77869269-1ef8ab80-7268-11ea-9548-3a456de85e75.png)

Link Figma: https://www.figma.com/file/osiuhNZsSfAUpEzZOdw61g/Vietcode-Website?node-id=81%3A2

Deadline cho issue này: 4 ngày.

**Comment by tiuphun** [comment]
Đây là trang web anh Sơn Ke đã tham khảo:
https://ilcoincrypto.com/ 💰 

Mn có thể inspect trang này rồi cop code về cũng đc code toàn bộ sẽ hơi lâu

**Comment by MyNameIsHung** [comment]
Nếu cái này chỉ có 3 phần thì bây giờ mọi người nhận phần luôn đi.
Em lấy phần Việt cốt qua những con số nhé. 
Cốt xong rồi ngồi ghép lại cũng đc em toàn làm thế.
