### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by duc0905** [vietcodes5/web#3]
Cải tiến cái Navbar (Header.js) để làm nó dễ nhìn hơn và sử dụng palette màu của anh Sơn ke.

Link Figma: https://www.figma.com/file/osiuhNZsSfAUpEzZOdw61g/Vietcode-Website?node-id=0%3A1

**Comment by MyNameIsHung** [comment]
Em xin cái này phát

**Comment by MyNameIsHung** [comment]
Thôi em đùa tí

**Comment by duc0905** [comment]
@MyNameIsHung Cái này DL 2 ngày nhé

**Comment by MyNameIsHung** [comment]
Anh cho em 4 ngày được không anh. 2 ngày tới em hơi bận. Em sẽ cố sắp xếp thời gian để làm được nhiều nhất có thể.

**Comment by duc0905** [comment]
Hong

**Comment by MyNameIsHung** [comment]
Trầm cảm time

**Comment by MyNameIsHung** [comment]
Em đùa đấy :v thế thì trông nó sẽ hơi không được chỉn chu lắm chắc em chỉ chỉnh lại style thôi k sửa component đâu
