### ISSUE TITLE
Create custom Theme with Material UI

### ISSUE THREAD

**Issue by duc0905** [vietcodes5/web#4]
Trong project đã và đang sử dụng Material UI nhưng đang sử dụng màu và default theme của họ. Tạo custom theme để phù hợp với design mà anh Sơn ke làm.

[Link Figma](https://www.figma.com/file/osiuhNZsSfAUpEzZOdw61g/Vietcode-Website?node-id=0%3A1)

[Material UI Theme](https://material-ui.com/customization/theming/)

**Comment by binclone123** [comment]
E (N Đức) xin cái này ạ

**Comment by binclone123** [comment]
Ơ mà issue thì DL là bao h ạ?

**Comment by duc0905** [comment]
Cái này xem phần Theme trên Material UI nhé. Có thể tham khảo code bên wweb-admin về phần này. DL cho cái này là 2 ngày nhé.
