### ISSUE TITLE
Create a common component for Post, Series, and Event covers

### ISSUE THREAD

**Issue by duc0905** [vietcodes5/web#6]
Hiện tại thì các cái cover của Post, Series, và Event đang có style rất giống nhau.

Ví dụ Series:

bình thường:
![image](https://user-images.githubusercontent.com/34796126/77051290-a559f580-69fd-11ea-9d19-024cc03d2665.png)

hover:
![image](https://user-images.githubusercontent.com/34796126/77051355-b9055c00-69fd-11ea-84e0-572bae268c9a.png)

Tạo 1 component để dùng chung cho cả 3 cái trên. Component sẽ nhận 3 props:
- title (dòng chữ to to lúc hover, ở trên là Dev tọc mạch)
- subtitle (dòng chữ nhỏ nhỏ lúc hover, ở trên là Lorem ipsom dolor)
- photoUrl (src của ảnh cover)

**Note**: Nên xem qua cách hoạt động của các component hiện tại trước, sau đó đọc code.

**Comment by binclone123** [comment]
E xin nhận ạ

**Comment by tiuphun** [comment]
@binclone123 join team đi mới nhận được issue cậu ơi
Có lời mời trong mail, hoặc check lại GitHub xem mình đã vào VietCode XTeam chưa nhé

**Comment by MyNameIsHung** [comment]
![image](https://user-images.githubusercontent.com/46376260/77246232-d897c100-6c57-11ea-9649-a7e2905ad230.png)

Em có ý tưởng chế cái ô events như thế này anh xem có được k anh

**Comment by MyNameIsHung** [comment]
Kiểu hover vào mình giảm cái opactiy của cái image ở sau đi khoảng .8 cho tối rồi cho cái description vào chính giữa, với tên của events viết bằng <h2> và subtitle viết bằng <h5>

**Comment by MyNameIsHung** [comment]
Kiểu hover vào mình giảm cái opactiy của cái image ở sau đi khoảng .8 cho tối rồi cho cái description vào chính giữa, với tên của events viết bằng h2 và subtitle viết bằng h5

**Comment by MyNameIsHung** [comment]
![image](https://user-images.githubusercontent.com/46376260/77246298-696e9c80-6c58-11ea-9dcf-4b6541bb1878.png)
Rồi cái phần "Other events" ấy em nghĩ anh nên thêm style cho :hover và :focus cho mấy cái box events.

**Comment by duc0905** [comment]
> ![image](https://user-images.githubusercontent.com/46376260/77246298-696e9c80-6c58-11ea-9dcf-4b6541bb1878.png)
> Rồi cái phần "Other events" ấy em nghĩ anh nên thêm style cho :hover và :focus cho mấy cái box events.

Phần này là task khác

**Comment by duc0905** [comment]
@binclone123 em làm xong chưa

**Comment by binclone123** [comment]
Update: Tạm e thất bại trong cái issue này, e xin chuyển cho người khác ạ.

**Comment by duc0905** [comment]
@binclone123 thôi ko sao, để anh làm nốt phần này. Anh làm xong thì em đọc code của anh để hiểu cách làm nhé.
