### ISSUE TITLE
Fix disappeared images in Home and About page

### ISSUE THREAD

**Issue by tiuphun** [vietcodes5/web#84]
Ở trang Home và About, ảnh không hiện. 
Nguyên nhân: là do người anh em thiện lành nào đó đã lười lấy thẳng link ảnh từ Facebook (và nó đã expired nên giờ k có ảnh).
![image](https://user-images.githubusercontent.com/54268723/88076548-66eb6780-cba4-11ea-8ce9-ebeba206eeda.png)
Cách khắc phục: 
💯 Tạo folder mới chứa ảnh cho từng page trong Firebase, up ảnh lên đấy
💯 Viết cú pháp request ảnh từ Firebase về tương tự như với trang Bài viết và Sự kiện
💯 Check, pull lên Git.

**Comment by MyNameIsHung** [comment]
Em có cách này nó tiện hơn là bỏ ảnh vào thư mục public rồi import vào có được k ạ. Giờ em sợ tạo folder ngồi bỏ ảnh rồi vt request thì hơi bị lâu.
